[package]
name = "fiskur"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
indicatif = {version= "0.17.9", features = ["rayon"]}
serde = "1.0.215"
serde_derive = "1.0.136"
toml = "0.8.19"
